name: Deploy Backend

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build backend Docker image
      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/iga-backend:latest ./backend

      # Push backend image to Docker Hub
      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/iga-backend:latest

      # Run backend container
      - name: Run backend container
        run: |
          echo "Backend DB URL: ${{ secrets.SPRING_DATASOURCE_URL }}"
          docker run -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
                     -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
                     -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
                     -p 8080:8080 \
                     ${{ secrets.DOCKER_USERNAME }}/iga-backend:latest
